Models/DB_CRUD.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CRUDEntities4 : DbContext
    {
        public CRUDEntities4()
            : base("name=CRUDEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gente> Gente { get; set; }
    }
}

Models/DB_CRUD.Designer.cs
// La generación de código T4 está habilitada para el modelo 'C:\ProjectsVS\MVC_CRUD\MVC_CRUD\Models\DB_CRUD.edmx'. 
// Para habilitar la generación de código heredada, cambie el valor de la propiedad del diseñador 'Estrategia de generación de código'
// por 'ObjectContext heredado'. Esta propiedad está disponible en la ventana Propiedades cuando se abre
// el modelo en el diseñador.

// Si no se ha generado ninguna clase de contexto y de entidad, puede que haya creado un modelo vacío pero
// no haya elegido todavía la versión de Entity Framework que se va a usar. Para generar una clase de contexto y clases de entidad
// para el modelo, abra el modelo en el diseñador, haga clic con el botón secundario en la superficie del diseñador y
// seleccione 'Actualizar modelo desde base de datos...', 'Generar base de datos desde modelo...' o 'Agregar elemento de generación
// de código...'.

Models/DB_CRUD.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

Models/Gente.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gente
    {
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public System.DateTime FechaNacimeiento { get; set; }
    }
}

Models/ViewModels/GenteviewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVC_CRUD.Models.ViewModels
{
    public class GenteviewModel
    {
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required]
        [StringLength(50)]
        [EmailAddress]
        public string Correo { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Nacimeinto")]
        [DisplayFormat(DataFormatString ="{0:yyyy-MM-dd}",ApplyFormatInEditMode = true)]
        public DateTime Fecha_Nacimiento { get; set; }
        
    }
}

Models/ViewModels/listatablaviewmodel.cs
using System;

namespace MVC_CRUD.Models.ViewModels
{
    public class listatablaviewmodel
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public string Correo { get; set; }
    }
}

Controllers/GenteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using MVC_CRUD.Models;
using MVC_CRUD.Models.ViewModels;

namespace MVC_CRUD.Controllers
{
    public class GenteController : Controller
    {
        // GET: Gente
        public ActionResult Index()
        {
            List<listatablaviewmodel> lst;
            using (CRUDEntities4 db = new CRUDEntities4())
            {
                lst = (from d in db.Gente
                       select new listatablaviewmodel
                       {
                           id = d.ID,
                           Nombre = d.Nombre,
                           Correo = d.Correo
                       }).ToList();
            }
            return View(lst);
        }
        public ActionResult Nuevo() 
        {
            return View();
        }
        [HttpPost]
        public ActionResult Nuevo (GenteviewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CRUDEntities4 db = new CRUDEntities4 ())
                    {
                        var Gente = new Gente();
                        
                        Gente.Correo = model.Correo;
                        Gente.FechaNacimeiento = model.Fecha_Nacimiento;
                        Gente.Nombre = model.Nombre;
                        
                        db.Gente.Add(Gente);
                        db.SaveChanges();
                    }
                
                   return Redirect("/Gente");
                }
                return View (model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }
        public ActionResult Editar(int Id)
        {
            GenteviewModel model = new GenteviewModel();
            using (CRUDEntities4 db = new CRUDEntities4())
            {
                var Gente = db.Gente.Find(Id);
                model.Nombre = Gente.Nombre;
                model.Correo = Gente.Correo;
                model.Fecha_Nacimiento = Gente.FechaNacimeiento;
                model.Id = Gente.ID;

            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Editar(GenteviewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (CRUDEntities4 db = new CRUDEntities4())
                    {
                        var Gente = db.Gente.Find(model.Id);

                        Gente.Correo = model.Correo;
                        Gente.FechaNacimeiento = model.Fecha_Nacimiento;
                        Gente.Nombre = model.Nombre;

                        db.Entry(Gente).State = System.Data.Entity.EntityState.Modified;
                        db.SaveChanges();
                    }

                    return Redirect("/Gente");
                }
                return View(model);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }

        }
        [HttpGet]
        public ActionResult eliminar( int Id)
        {
            using (CRUDEntities4 db = new CRUDEntities4())
            {
                var otabla = db.Gente.Find(Id);
                db.Gente.Remove(otabla);
                db.SaveChanges();
            }
            return Redirect("/Gente");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC_CRUD.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Views/Gente/Editar.cshtml
@model MVC_CRUD.Models.ViewModels.GenteviewModel
@{
    ViewBag.Title = "Update";
}

<h2> @ViewBag.Title</h2>

@using (Html.BeginForm("Editar", "Gente", FormMethod.Post))
{
    <div class="row">
        <div clas="col-md-12">
            @Html.HiddenFor(d=>d.Id)
            <div>
                @Html.LabelFor(d => d.Nombre)
                @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Correo)
                @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
            </div>
            <div>
                @Html.LabelFor(d => d.Fecha_Nacimiento) <br />
                @Html.EditorFor(d => d.Fecha_Nacimiento, "", new { @class = "form-control" })
                @Html.ValidationMessageFor(d => d.Fecha_Nacimiento, null, new { @class = "red" })
            </div>
            <div style="text-align:right;">
                <input value="Guardar" class="btn btn-primary" type="submit" />

            </div>

        </div>

    </div>
}

Views/Gente/Index.cshtml
@model List<MVC_CRUD.Models.ViewModels.listatablaviewmodel>
@{
    ViewBag.Title = "Mis Datos";
}

<h2>@ViewBag.Title</h2>

<div style="text-align:right;padding:5px">
    <a href="~/Gente/Nuevo" class="btn btn-primary">Nuevo</a>
</div>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <tr>
                <th>#</th>
                <th>NOMBRE</th>
                <th>Correo</th>
            </tr>
            @foreach (var Elemento in Model)
            {
                <tr>
                    <td>@Elemento.id</td>
                    <td>@Elemento.Nombre</td>
                    <td>@Elemento.Correo</td>
                    <td>
                        <a class="btn btn-dark" href="~/Gente/Editar/@Elemento.id">Editar</a>
                        <a class="btn btn-danger" href="~/Gente/Eliminar/@Elemento.id">Eliminar</a>
                    </td>
                </tr>
            }
        </table>

    </div>

</div>

Views/Gente/Nuevo.cshtml
@model MVC_CRUD.Models.ViewModels.GenteviewModel
@{
    ViewBag.Title = "Nuevo";
}

<h2> @ViewBag.Title</h2>

@using (Html.BeginForm("Nuevo","Gente",FormMethod.Post))
{
<div class="row">
    <div clas="col-md-12">
        <div>
            @Html.LabelFor(d => d.Nombre)
            @Html.TextBoxFor(d => d.Nombre, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Nombre, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.Correo)
            @Html.TextBoxFor(d => d.Correo, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Correo, null, new { @class = "red" })
        </div>
        <div>
            @Html.LabelFor(d => d.Fecha_Nacimiento) <br />
            @Html.EditorFor(d => d.Fecha_Nacimiento, "", new { @class = "form-control" })
            @Html.ValidationMessageFor(d => d.Fecha_Nacimiento, null, new { @class = "red" })
        </div>
                <div style="text-align:right;">
                    <input value="Guardar" class="btn btn-primary" type="submit" />

                </div>

         </div>

    </div>
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Hola Mundo desde MVC Net.Framework</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>